appName: 711-community
domain: ha-ving.store

replicaCount: 3
image:
  repositoryHost: harbor.ha-ving.store
  imageName: {{ .Values.appName }}
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: {{ .Values.appName }}.ha-ving.store
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: {{ .Values.appName }}-ingress
      hosts:
        - {{ .Values.appName }}.ha-ving.store

resources: # 리소스 제한 및 요청
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
