appName: community
domain: ha-ving.store

replicaCount: 3
image:
  repositoryHost: harbor.ha-ving.store
  imageName: community
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: community.ha-ving.store
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: community-ingress
      hosts:
        - community.ha-ving.store

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
